### ISSUE TITLE
En español

### ISSUE THREAD

**Issue by hanzo2001** [JDBS/Roguelike#1]
Sería mejor programar en inglés ^_^

**Comment by JDBS** [comment]
Cierto, pero iba a exponerlo a la clase mas adelante por eso elegí hacerlo
en español. (Tengo problemas con la ñ T.T)

2016-11-02 12:22 GMT+00:00 hanzo2001 notifications@github.com:

**Comment by JDBS** [comment]
Traduciré el proyecto más adelante cuando tenga tiempo aunque sea contraproducente.
